-- MySQL Script generated by MySQL Workbench
-- Qua 23 Mar 2016 13:38:05 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema ciclope
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ciclope
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ciclope` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ciclope` ;

-- -----------------------------------------------------
-- Table `ciclope`.`ipes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ciclope`.`ipes` ;

CREATE TABLE IF NOT EXISTS `ciclope`.`ipes` (
  `sigla` VARCHAR(10) NOT NULL,
  `lat` DECIMAL(11,8) NOT NULL,
  `lng` DECIMAL(11,8) NOT NULL,
  `logradouro` VARCHAR(100) NULL,
  `bairro` VARCHAR(50) NULL,
  `cidade` VARCHAR(100) NULL,
  `estado` VARCHAR(2) NULL,
  `cep` VARCHAR(8) NULL,
  `telefone` VARCHAR(20) NULL,
  `url` VARCHAR(100) NULL,
  `url2` VARCHAR(100) NULL,
  PRIMARY KEY (`sigla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciclope`.`polos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ciclope`.`polos` ;

CREATE TABLE IF NOT EXISTS `ciclope`.`polos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cidade` VARCHAR(100) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `lat` DECIMAL(11,8) NULL,
  `lng` DECIMAL(11,8) NULL,
  `nome_polo` VARCHAR(100) NOT NULL,
  `nome_fantasia` VARCHAR(100) NULL,
  `logradouro` VARCHAR(100) NULL,
  `numero` VARCHAR(10) NULL,
  `bairro` VARCHAR(45) NULL,
  `cep` VARCHAR(8) NULL,
  `complemento` VARCHAR(100) NULL,
  `conceito` VARCHAR(2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciclope`.`cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ciclope`.`cursos` ;

CREATE TABLE IF NOT EXISTS `ciclope`.`cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ipes_sigla` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `ipes_sigla`),
  INDEX `fk_cursos_ipes1_idx` (`ipes_sigla` ASC),
  CONSTRAINT `fk_cursos_ipes1`
    FOREIGN KEY (`ipes_sigla`)
    REFERENCES `ciclope`.`ipes` (`sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciclope`.`oferta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ciclope`.`oferta` ;

CREATE TABLE IF NOT EXISTS `ciclope`.`oferta` (
  `polos_id` INT NOT NULL,
  `cursos_id` INT NOT NULL,
  `data_oferta` DATE NULL,
  `numero_vagas` INT NULL,
  `oferta_id` INT NOT NULL,
  PRIMARY KEY (`polos_id`, `cursos_id`, `oferta_id`),
  INDEX `fk_polos_has_cursos_cursos1_idx` (`cursos_id` ASC),
  INDEX `fk_polos_has_cursos_polos1_idx` (`polos_id` ASC),
  CONSTRAINT `fk_polos_has_cursos_polos1`
    FOREIGN KEY (`polos_id`)
    REFERENCES `ciclope`.`polos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_polos_has_cursos_cursos1`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `ciclope`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
