-- MySQL Script generated by MySQL Workbench
-- Sáb 13 Jan 2018 18:18:41 -02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ciclope
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ciclope
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ciclope` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ciclope` ;

-- -----------------------------------------------------
-- Table `ciclope`.`ipes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ciclope`.`ipes` ;

CREATE TABLE IF NOT EXISTS `ciclope`.`ipes` (
  `id` INT NOT NULL DEFAULT 0,
  `lat` DECIMAL(11,8) NULL,
  `lng` DECIMAL(11,8) NULL,
  `sigla` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(100) NULL,
  `logradouro` VARCHAR(100) NULL,
  `bairro` VARCHAR(50) NULL,
  `complemento` VARCHAR(100) NULL,
  `cidade` VARCHAR(100) NULL,
  `estado` VARCHAR(2) NULL,
  `cep` VARCHAR(8) NULL,
  `telefone` VARCHAR(20) NULL,
  `url` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciclope`.`polos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ciclope`.`polos` ;

CREATE TABLE IF NOT EXISTS `ciclope`.`polos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cidade` VARCHAR(100) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `lat` DECIMAL(11,8) NULL,
  `lng` DECIMAL(11,8) NULL,
  `nome_polo` VARCHAR(100) NOT NULL,
  `nome_fantasia` VARCHAR(100) NULL,
  `logradouro` VARCHAR(100) NULL,
  `numero` VARCHAR(10) NULL,
  `bairro` VARCHAR(45) NULL,
  `cep` VARCHAR(8) NULL,
  `complemento` VARCHAR(100) NULL,
  `conceito` VARCHAR(2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciclope`.`ipes_has_polos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ciclope`.`ipes_has_polos` ;

CREATE TABLE IF NOT EXISTS `ciclope`.`ipes_has_polos` (
  `ipes_id` INT NOT NULL,
  `polos_id` INT NOT NULL,
  PRIMARY KEY (`ipes_id`, `polos_id`),
  INDEX `fk_ipes_has_polos_polos1_idx` (`polos_id` ASC),
  INDEX `fk_ipes_has_polos_ipes_idx` (`ipes_id` ASC),
  CONSTRAINT `fk_ipes_has_polos_ipes`
    FOREIGN KEY (`ipes_id`)
    REFERENCES `ciclope`.`ipes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ipes_has_polos_polos1`
    FOREIGN KEY (`polos_id`)
    REFERENCES `ciclope`.`polos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
